#!/usr/bin/env bash

#  Script: inputrc.bash
# Purpose: This file is a configuration file for GNU Readline library
# Created: May 04, 2018
#  Author: <B>H</B>ugo <B>S</B>aporetti <B>J</B>unior
#  Mailto: homesetup@gmail.com
#    Site: https://github.com/yorevs/homesetup
# License: Please refer to <https://opensource.org/licenses/MIT>
#
# Copyright (c) 2024, HomeSetup team

# inspiRED by: https://www.shell-tips.com/bash/shortcuts/#gsc.tab=0

# Preserve system wide settings.
$include /etc/inputrc

# Preferences -----------------------------------------------------------

# Ensure all binding keeps the default Emacs behavior.
# Most common in a Bash shell environment, even for vi users.
set editing-mode emacs

# Ignore case when doing auto-completion.
set completion-ignore-case on

# Enable completion coloring.
set colored-stats on
set colored-completion-prefix on

# Do not bell on tab-completion (use the visible bell).
set bell-style visible

# Complete Options -------------------------------------------------------

# Treat hypen and underscores as equivalent.
set completion-map-case on

# The number of completions to display without prompt; when exceeded a
# prompt-to-display will appear.
set completion-query-items 200

# Display the common prefix choices on the first completion then cycle the
# available choices on the next completion.
set menu-complete-display-prefix on

# Turn off the completions pager.
set page-completions off

# Display the list of matches when no further completion is possible.
set show-all-if-unmodified on

# Immediately display completion matches.
set show-all-if-ambiguous on

# Smartly complete items when the cursor is not at the end of the line.
set skip-completed-text on
